web:
  build: .
  command: foreman start
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - database
    - redis
    - tika
    - elasticsearch
#   - nomenklatura
    - s3
    - mailcatcher
  environment:
    RESQUE_SERVER_OPEN: true
    ELASTICSEARCH_URL: http://elasticsearch:9200/
    REDIS_URL: redis://redis:6379
    DATABASE_URL: postgres://kleineanfragen:@database/kleineanfragen
    TIKA_SERVER_URL: http://tika:9998
#   NOMENKLATURA_HOST: http://nomenklatura:8080
#   NOMENKLATURA_APIKEY: change_me

database:
  build: contrib/postgres-ka
  environment:
    POSTGRES_USER: kleineanfragen
# ports:
#   - "5432:5432"

redis:
  image: redis

tika:
  image: logicalspark/docker-tikaserver
# ports:
#   - "9998:9998"

elasticsearch:
  image: dockerfile/elasticsearch
## if you want to use elasticsearch head (standalone):
#  command: /elasticsearch/bin/elasticsearch -Des.http.cors.enabled=true
#  ports:
#    - "9200:9200"

#nomenklatura:
# image: robbi5/nomenklatura
# links:
#   - database
# environment:
#   DATABASE_URL: postgres://kleineanfragen:@database/nomenklatura
#   SECRET_KEY: change_me
#   GITHUB_CLIENT_ID: change_me
#   GITHUB_CLIENT_SECRET: change_me
# ports:
#   - "8080:8080"

s3:
  build: contrib/s3ninja
  volumes:
    - ./tmp/ka-dev:/data
  ports:
    - "9444:9444"

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"