credentials: &credentials
  provider: AWS
  aws_access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['S3_SECRET_KEY'] %>
  path_style: true
  aws_signature_version: 2

development:
  <<: *credentials
  endpoint: http://s3:9444
  region: nil
  bucket: ka-dev
  # don't panic, these are fake (see s3ninja/app/application.conf)
  aws_access_key_id: AKIAIOSFODNN7EXAMPLE
  aws_secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

test:
  provider: Local
  local_root: <%= Rails.root.join 'tmp' %>
  bucket: ka-test

production:
  <<: *credentials
  host: s3.kleine-anfragen.de
  bucket: ka-prod